###############################################################################
# Create users with ssh keys
###############################################################################

- name: Create local linux users with ssh keys
  include_tasks: linux-users.yml
  with_items: "{{ linux_users }}"
